development:
  bucket_name: backjam_development
  access_key_id: 0FZPCHGVB8KQHD7NDWR2
  secret_access_key: //cWPrw3NJzg3ZsXv5IbCyeegSTWTPtTkEKtzoAm 

test:
  bucket_name: backjam_test
  access_key_id: 0FZPCHGVB8KQHD7NDWR2
  secret_access_key: //cWPrw3NJzg3ZsXv5IbCyeegSTWTPtTkEKtzoAm 

production:
  bucket_name: backjam
  access_key_id: 0FZPCHGVB8KQHD7NDWR2
  secret_access_key: //cWPrw3NJzg3ZsXv5IbCyeegSTWTPtTkEKtzoAm 
